log:
  level: INFO

entryPoints:
  web:
    # http
    address: ":80"

http:
  routers:
    app-router:
      rule: "Host(`smart48.local`)"
      entryPoints:
        - web
      middlewares:
        - csrf
      service: app

  middlewares:
    csrf:
      # https://docs.traefik.io/master/middlewares/headers/#hostsproxyheaders
      # https://docs.djangoproject.com/en/dev/ref/csrf/#ajax
      headers:
        hostsProxyHeaders: ["X-CSRFToken"]

  services:
    app:
      loadBalancer:
        servers:
          - url: http://nginx:8880

providers:
  # https://docs.traefik.io/master/providers/file/
  file:
    filename: /etc/traefik/traefik.yml
    watch: true
